config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'meu_contato', to: 'static_pages#meu_contato'
  
  resources :contatos
  resources :users, only: [:new, :create]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    #has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence:true, length: { maximum: 50 }
    validates :password_digest, length: { minimum:6 }   
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: %i[ show edit update destroy ]

  # GET /contatos or /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1 or /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos or /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to contato_url(@contato), notice: "Contato was successfully created." }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1 or /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to contato_url(@contato), notice: "Contato was successfully updated." }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1 or /contatos/1.json
  def destroy
    @contato.destroy

    respond_to do |format|
      format.html { redirect_to contatos_url, notice: "Contato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contato_params
      params.require(:contato).permit(:name, :phone)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
  def index
    @nome = "Bruno" 
  end    

  def sobre
    
  end  

  def meu_contato
     
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
    @user = User.new
end
    
def create
end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contatos/_contato.html.erb
<div id="<%= dom_id contato %>">
  <p>
    <strong>Name:</strong>
    <%= contato.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contato.phone %>
  </p>

</div>

app/views/contatos/_form.html.erb
<%= form_with(model: contato) do |form| %>
  <% if contato.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
        <% contato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing contato</h1>

<%= render "form", contato: @contato %>

<br>

<div>
  <%= link_to "Show this contato", @contato %> |
  <%= link_to "Back to contatos", contatos_path %>
</div>

app/views/contatos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contatos</h1>

<div id="contatos">
  <% @contatos.each do |contato| %>
    <%= render contato %>
    <p>
      <%= link_to "Show this contato", contato %>
    </p>
  <% end %>
</div>

<%= link_to "New contato", new_contato_path %>

app/views/contatos/new.html.erb
<h1>New contato</h1>

<%= render "form", contato: @contato %>

<br>

<div>
  <%= link_to "Back to contatos", contatos_path %>
</div>

app/views/contatos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contato %>

<div>
  <%= link_to "Edit this contato", edit_contato_path(@contato) %> |
  <%= link_to "Back to contatos", contatos_path %>

  <%= button_to "Destroy this contato", @contato, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Contact. Todos os direitos reservados.', root_path %>
    </small>

    <nav>
        <ul>
            <li>
                <%= link_to 'Sobre',sobre_path %>
            </li>
            <li>
                <%= link_to 'Contato',meu_contato_path %>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">
      
        <li class="active">
        	<a href="#">Nova Conta</a>
        </li>
      
    </ul>

    <ul class="nav navbar-nav navbar-right">

    <li>
    	<%= link_to 'Entrar', '#' %>
    </li>
      
          

    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Contact</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>
<p>
    Entre em contato com <a href="https://github.com/JadsonLago">JadsonLago</a>, para saber mais sobre o sistema Contact.
</p>

app/views/static_pages/index.html.erb
<div class ="jumbotron">
    <h2>Contact</h2>
    <p>
    Gerencie seus contatos em qualquer lugar!
    </p>
    <p>
     <%= link_to 'Crie sua conta', '#', class: 'btn btn-primary bnt-lg' %>
    </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>
<p>
    O Sistema Contact foi projetado para aprendizagem e pratica do framework Ruby on Rails.
</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Cadastra-se</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>